<div><p style="color:#6a66bd; text-align:center; font-weight:bold; font-family:verdana; font-size:25px;">NumPy - A Complete Guide</p></div>

---

<p style="text-align:right; font-family:verdana;">Follow <a href="https://github.com/TheMrityunjayPathak" style="color:#6a66bd; text-decoration:none;">@Mrityunjay Pathak</a> for more!</p>

<!--Include Prism.js and CSS-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.25.0/themes/prism.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.25.0/prism.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.25.0/components/prism-python.min.js"></script>
    
<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Introduction to Numpy</font>
<br>
<br>
<strong>What is NumPy?</strong>
<br>
• NumPy stands for Numerical Python.
<br>
• NumPy is a Python library used for working with arrays.
<br>
• It also has functions for working in domain of linear algebra, fourier transform and matrices.
<br>
• NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
<br>
<br>
<strong>Why Use NumPy?</strong>
<br>
• In Python we have lists that serve the purpose of arrays, but they are slow to process.
<br>
• NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
<br>
• The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
<br>
• Arrays are very frequently used in data science, where speed and resources are very important.
<br>
<br>
<strong>Why is NumPy Faster Than Lists?</strong>
<br>
• NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
<br>
• This behavior is called locality of reference in computer science.
<br>
• This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.
</div>

<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Installing NumPy</font>
<br>
<br>
• If you have <a href="https://www.python.org/downloads/" style="text-decoration:none; color:#6a66bd;">Python</a> and <a href="https://pypi.org/project/pip/" style="text-decoration:none; color:#6a66bd;">PIP</a> already installed on your system, then installation of NumPy is very easy.
<br>
• Install it using this command :
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> You can use your Jupyter Notebook as Terminal to install anything using PIP Command.
</div>
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> Just add an exclamation mark before your PIP Command. Like !pip install numpy
</div>
</div>

In [7]:
!pip install numpy

<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Getting Started with NumPy</font>
<br>
<br>
<strong>Import NumPy</strong>
<br>
• Once NumPy is installed, import it in your project by adding the import keyword.
</div>

In [8]:
import numpy

<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>NumPy as np</strong>
<br>
• NumPy is usually imported under the np alias.
<br>
• Create an alias with the as keyword while importing.
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> In Python alias are an alternate name for referring to the same thing.
</div>
</div>

In [9]:
import numpy as np

<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Checking NumPy Version</strong>
<br>
• The version string is stored under __version__ attribute.
</div>

In [10]:
print(numpy.__version__)

1.26.3


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Creating NumPy Array</font>
<br>
<br>
<strong>NumPy ndarray Object</strong>
<br>
• NumPy is used to work with arrays. The array object in NumPy is called ndarray.
<br>
• We can create a NumPy ndarray object by using the array() function.
<br>
• In computer programming, an array is a structure for storing and retrieving data. 
<br>
• We often talk about an array as if it were a grid in space, with each cell storing one element of the data.
<br>
<br>
<strong>Most NumPy arrays have some restrictions, For instance :</strong>
<br>
• All elements of the array must be of the same type of data.
<br>
• Once created, the total size of the the array can’t change.
<br>
• The shape must be “rectangular” not “jagged”.
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> type() function tells us the type of the object passed to it.
</div>
</div>

In [11]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.
</div>

In [12]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Create Basic Arrays</font>
<br>
<br>
• Besides creating an array from a sequence of elements, you can easily create an array of some predefined formats.
<br>
• To create an array with all elements as zero(0).
</div>

In [13]:
#Creating a 1D Array
zeros = np.zeros(3)
print(zeros)

[0. 0. 0.]


In [14]:
#Creating a 2D Array
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• To create an array with all elements as one(1).
</div>

In [15]:
#Creating a 1D Array
ones = np.ones(3)
print(ones)

[1. 1. 1.]


In [16]:
#Creating a 2D Array
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• The function empty() creates an array whose initial content is random and depends on the state of the memory. 
<br>
• The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards.
</div>

In [17]:
#Create a 1D Array
empty = np.empty(3)
print(empty)

[1. 1. 1.]


In [18]:
#Create a 2D Array
empty = np.empty((3,3))
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• To create an array with all digonal elements as one(1).
</div>

In [19]:
idnt = np.identity(3)
print(idnt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• To create an array with all digonal elements as specified.
</div>

In [20]:
dig = np.diag((1,2,3))
print(dig)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• To create an array with series of numbers starting with zero.
</div>

In [21]:
#To start with 0
rng = np.arange(9)
print(rng)

[0 1 2 3 4 5 6 7 8]


In [22]:
#To start with any specific number and interval (step) specified
rng = np.arange(1, 10, 2)
print(rng)

[1 3 5 7 9]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• You can also use linspace() method to create an array with values that are spaced linearly in a specified interval.
</div>

In [23]:
lin_arr = np.linspace(0, 10, num=5)
print(lin_arr)

[ 0.   2.5  5.   7.5 10. ]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• The tile() method constructs an array by repeating arrays.
<br>
• You can specify repetitions to create an array by repeating the array any number of times.
</div>

In [24]:
#Create an array by repeating arr 2 times
arr = np.array([1,2,3,4,5])
tile_arr = np.tile(arr, 2)
print(tile_arr)

[1 2 3 4 5 1 2 3 4 5]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• The full() method creates a new array of given shape and type, filled with a given fill value.
</div>

In [25]:
#Create a 2X2 array filled with 3s
arr = np.full((2,2),3)
print(arr)

[[3 3]
 [3 3]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Dimensions in Arrays</font>
<br>
<br>
• A dimension in arrays is one level of array depth.
<br>
<br>
<strong>0-D Arrays</strong>
<br>
• 0-D arrays or Scalars are the elements in an array. Each value in an array is a 0-D array.
</div>

In [26]:
arr = np.array(42)
print(arr)

42


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>1-D Arrays</strong>
<br>
• An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
<br>
• These are the most common and basic arrays.
</div>

In [27]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>2-D Arrays</strong>
<br>
• An array that has 1-D arrays as its elements is called a 2-D array.
<br>
• These are often used to represent matrix or 2nd order tensors.
</div>

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>3-D arrays</strong>
<br>
• An array that has 2-D arrays (matrices) as its elements is called 3-D array.
<br>
• These are often used to represent a 3rd order tensor.
</div>

In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Check Number of Dimensions?</strong>
<br>
• NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
</div>

In [30]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Higher Dimensional Arrays</strong>
<br>
• An array can have any number of dimensions.
<br>
• When the array is created, you can define the number of dimensions by using the ndmin argument.
</div>

In [31]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Dimension of Array :', arr.ndim)

[[[[[1 2 3 4]]]]]
Dimension of Array : 5


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Indexing Array</font>
<br>
<br>
<strong>Access Array Elements</strong>
<br>
• Array indexing is the same as accessing an array element.
<br>
• You can access an array element by referring to its index number.
<br>
• The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.
</div>

In [32]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Access 2-D Arrays</strong>
<br>
• To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
<br>
• Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.
</div>

In [33]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st row :', arr[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row : 2


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Access 3-D Arrays</strong>
<br>
• To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.
</div>

In [34]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print('3rd element of the second array of the first array :', arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3rd element of the second array of the first array : 6


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Negative Indexing</strong>
<br>
• Use negative indexing to access an array from the end.
</div>

In [35]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('Last element from last row :', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from last row : 10


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Slicing Array</font>
<br>
<br>
<strong>Slicing Arrays</strong>
<br>
• Slicing in python means taking elements from one given index to another given index.
<br>
• We pass slice instead of index like this : [start:end].
<br>
• We can also define the step, like this : [start:end:step].
<br>
• If we don't pass start its considered 0
<br>
• If we don't pass end its considered length of array in that dimension
<br>
• If we don't pass step its considered 1
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> The result includes the start index, but excludes the end index.
</div>
</div>

In [36]:
#Slice elements from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [37]:
#Slice elements from index 4 to the end of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [38]:
#Slice elements from the beginning to index 4 (not included)
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Negative Slicing</strong>
<br>
• Use the minus operator to refer to an index from the end.
</div>

In [39]:
#Slice from the index 3 from the end to index 1 from the end
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Step</strong>
<br>
• Use the step value to determine the step of the slicing.
</div>

In [40]:
#Return every other element from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Slicing 2-D Arrays</strong>
</div>

In [41]:
#From the second element, slice elements from index 1 to index 4
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [42]:
#From both elements, return index 2
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [43]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Data Types in NumPy</font>
<br>
<br>
• NumPy has some extra data types and refer to data types with one character like i for integers, u for unsigned integers etc.
<br>
• Below is a list of all data types in NumPy and the characters used to represent them.
<br>
<strong>i</strong> - integer
<br>
<strong>b</strong> - boolean
<br>
<strong>u</strong> - unsigned integer
<br>
<strong>f</strong> - float
<br>
<strong>c</strong> - complex float
<br>
<strong>m</strong> - timedelta
<br>
<strong>M</strong> - datetime
<br>
<strong>O</strong> - object
<br>
<strong>S</strong> - string
<br>
<strong>U</strong> - unicode string
<br>
<strong>V</strong> - fixed chunk of memory for other type (void)
<br>
<br>
<strong>Checking the Data Type of an Array</strong>
<br>
• The NumPy array object has a property called dtype that returns the data type of the array.
</div>

In [44]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Creating Arrays With a Defined Data Type</strong>
<br>
• We use the array() function to create arrays, this function can take an optional argument : dtype that allows us to define the expected data type of the array elements.
</div>

In [45]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• For i, u, f, S and U we can define size for the datatype also.
</div>

In [46]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Converting Data Type on Existing Arrays</strong>
<br>
• The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
<br>
• The astype() function creates a copy of the array and allows you to specify the data type as a parameter.
<br>
• The data type can be specified using a string, like 'f' for float, 'i' for integer etc. 
<br>
• Or you can use the data type directly like float for float and int for integer.
</div>

In [47]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Array Copy vs View</font>
<br>
<br>
<strong>Difference Between Copy and View</strong>
<br>
• The main difference between a copy and a view of an array is that the copy is a new array and the view is just a view of the original array.
<br>
• The copy owns the data and any changes made to the copy will not affect original array and any changes made to the original array will not affect the copy.
<br>
• The view does not own the data and any changes made to the view will affect the original array and any changes made to the original array will affect the view.











</div>

In [48]:
#Make a copy, change the original array and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [49]:
#Make a view, change the original array and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Check if Array Owns its Data</strong>
<br>
• Copies owns the data and views does not own the data, but how can we check this?
<br>
• Every NumPy array has the attribute base that returns None if the array owns the data.
<br>
• Otherwise, the base attribute refers to the original object.
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> The copy returns None.
</div>
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> The view returns the original array.
</div>
</div>

In [50]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Array Size</font>
<br>
<br>
• To find the total number of elements in the array, use the size function of NumPy.
</div>

In [51]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.size)

[[1 2 3 4]
 [5 6 7 8]]
8


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Array Shape</font>
<br>
<br>
<br>
<strong>Shape of an Array</strong>
<br>
• The shape of an array is the number of elements in each dimension.
<br>
<br>
<strong>Get the Shape of an Array</strong>
<br>
• NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.
</div>

In [52]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Reshaping Array</font>
<br>
<br>
<strong>Reshaping Arrays</strong>
<br>
• Reshaping means changing the shape of an array.
<br>
• The shape of an array is the number of elements in each dimension.
<br>
• By reshaping we can add or remove dimensions or change number of elements in each dimension.
</div>

In [53]:
#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [54]:
#Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Can We Reshape Into any Shape?</strong>
<br>
• Yes, as long as the elements required for reshaping are equal in both shapes.
<br>
• We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
</div>

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(4, 2)
print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Returns Copy or View?</strong>
<br>
• Check if the returned array in reshape is a copy or a view.
</div>

In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base) #It is a view as it returns original array

[1 2 3 4 5 6 7 8]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Unknown Dimension</strong>
<br>
• You are allowed to have one "unknown" dimension.
<br>
• Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
<br>
• Pass -1 as the value and NumPy will calculate this number for you.
</div>

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Flattening Arrays</font>
<br>
<br>
• Flattening array means converting a multidimensional array into a 1D array.
<br>
• We can use reshape(-1) to do this.
</div>

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• arr.ravel() can also be used to flatten an array.
</div>

In [59]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr = arr.ravel()
print(newarr)

[1 2 3 4 5 6 7 8 9]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• You can use flatten() to flatten your array into a 1D array.
</div>

In [60]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr = arr.flatten()
print(newarr)

[1 2 3 4 5 6 7 8 9]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Reversing an Array</font>
<br>
<br>
• np.flip() function allows you to flip or reverse the contents of an array along an axis. 
<br>
• When using np.flip(), specify the array you would like to reverse and the axis. 
<br>
• If you don’t specify the axis, NumPy will reverse the contents along all of the axes of your input array.
</div>

In [61]:
#Reversing an 1D Array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = np.flip(arr)

print(arr)

print(newarr)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [62]:
#Reversing an 2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr = np.flip(arr)

print(arr)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Unique Elements</font>
<br>
<br>
• You can find the unique elements in an array easily with np.unique.
</div>

In [63]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
newarr = np.unique(arr)
print(newarr)

[11 12 13 14 15 16 17 18 19 20]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• To get the index of unique values in a NumPy array, just pass the return_index argument in np.unique() function.
</div>

In [64]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
newarr, index_list = np.unique(arr, return_index=True)
print(newarr)
print(index_list)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array.
</div>

In [65]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
newarr, count_list = np.unique(arr, return_counts=True)
print(newarr)
print(count_list)

[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Iterating Array</font>
<br>
<br>
<strong>Iterating Arrays</strong>
<br>
• Iterating means going through elements one by one.
<br>
• As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
<br>
• If we iterate on a 1-D array it will go through each element one by one.
</div>

In [66]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Iterating 2-D Arrays</strong>
<br>
• In a 2-D array it will go through all the rows.
</div>

In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [68]:
#Iterate on each scalar element of the 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Iterating 3-D Arrays</strong>
<br>
• In a 3-D array it will go through all the 2-D arrays.
</div>

In [69]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [70]:
#Iterate on each scalar element of the 2-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Iterating Arrays Using nditer()</strong>
<br>
• The function nditer() is a helping function that can be used from very basic to very advanced iterations. 
<br>    
• It solves some basic issues which we face in iteration, lets go through it with examples.
</div>

In [71]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Iterating With Different Step Size</strong>
<br>
• We can use filtering and followed by iteration.
</div>

In [72]:
#Iterate through every scalar element of the 2D array skipping 1 element
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Enumerated Iteration Using ndenumerate()</strong>
<br>
• Enumeration means mentioning sequence number of somethings one by one.
<br>
• Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those use cases.
</div>

In [73]:
#Enumerate on following 1D arrays elements
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [74]:
#Enumerate on following 2D arrays elements
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Joining Array</font>
<br>
<br>
<strong>Joining NumPy Arrays</strong>
<br>
• Joining means putting contents of two or more arrays in a single array.
<br>
• We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. 
<br>
• If axis is not explicitly passed, it is taken as 0.
<br>
→ Axis 0 = Rows
<br>
→ Axis 1 = Columns  
</div>

In [75]:
#Join two 1-D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [76]:
#Join two 2-D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Joining Arrays Using Stack Functions</strong>
<br>
• Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
<br>
• We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
<br>
• We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.
</div>

In [77]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Stacking Along Rows</strong>
<br>
• NumPy provides a helper function : hstack() to stack along rows.
</div>

In [78]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Stacking Along Columns</strong>
<br>
• NumPy provides a helper function : vstack() to stack along columns.
</div>

In [79]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Stacking Along Height (depth)</strong>
<br>
• NumPy provides a helper function : dstack() to stack along height, which is the same as depth.
</div>

In [80]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Splitting Array</font>
<br>
<br>
<strong>Splitting NumPy Arrays</strong>
<br>
• Splitting is reverse operation of Joining.
<br>
• Joining merges multiple arrays into one and Splitting breaks one array into multiple.
<br>
• We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> The return value is a list containing three arrays.
</div>
</div>

In [81]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [82]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Split Into Arrays</strong>
<br>
• The return value of the array_split() method is an array containing each of the split as an array.
<br>
• If you split an array into 3 arrays, you can access them from the result just like any array element.
</div>

In [83]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Splitting 2-D Arrays</strong>
<br>
• Use the same syntax when splitting 2-D arrays.
<br>
• Use the array_split() method, pass in the array you want to split and the number of splits you want to do.
</div>

In [84]:
#Split the 2-D array into three 2-D arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• In addition, you can specify which axis you want to do the split around.
</div>

In [85]:
#Split the 2-D array into three 2-D arrays along columns
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [86]:
#Split the 2-D array into three 2-D arrays with hsplit()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [87]:
#Split the 2-D array into three 2-D arrays using vsplit()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Searching Arrays</font>
<br>
<br>
<strong>Searching Arrays</strong>
<br>
• You can search an array for a certain value and return the indexes that get a match.
<br>
• To search an array, use the where() method.
<br>
• It returns a tuple after finding elements according to condition.
</div>

In [88]:
#Find the indexes where the value is 4
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [89]:
#Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Search Sorted</strong>
<br>
• There is a method called searchsorted() which performs a binary search in the array and returns the index where the specified value would be inserted to maintain the search order.
<br>
• The searchsorted() method is assumed to be used on sorted arrays.
<br>
• The method starts the search from the left and returns the first index where the number is no longer larger than the next value.
</div>

In [90]:
#Find the indexes where the value 7 should be inserted
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Search From the Right Side</strong>
<br>
• By default the left most index is returned, but we can give side='right' to return the right most index instead.
</div>

In [91]:
#Find the indexes where the value 7 should be inserted, starting from the right
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Multiple Values</strong>
<br>
• To search for more than one value, use an array with the specified values.
</div>

In [92]:
#Find the indexes where the values 2, 4, and 6 should be inserted
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Non Zero Elements</strong>
<br>
• The NumPy nonzero() method finds the indices of array elements that are not zero.
</div>

In [93]:
arr = np.array([1, 0, 0, 4, -5])
non_zero_arr = np.nonzero(arr)
print(non_zero_arr)

(array([0, 3, 4], dtype=int64),)


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Elements wise Searching</strong>
<br>
• The argmax() method returns the index of the largest element of an array.
<br>
• Similarly, argmin() method returns the index of the smallest element of an array.
</div>

In [94]:
arr = np.array([71,4,7,65,91,12,8])
print("Index of largest element :", np.argmax(arr))
print("Index of smallest element :", np.argmin(arr))

Index of largest element : 4
Index of smallest element : 1


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Sorting Arrays</font>
<br>
<br>
<strong>Sorting Arrays</strong>
<br>
• Sorting means putting elements in an ordered sequence.
<br>
• Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
<br>
• The NumPy ndarray object has a function called sort() that will sort a specified array.
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> This method returns a copy of the array leaving the original array unchanged.
</div>

In [95]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• You can also sort arrays of strings or any other data type.
</div>

In [96]:
#Sort the array alphabetically
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [97]:
#Sort a boolean array
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Sorting a 2-D Array</strong>
<br>
• If you use the sort() method on a 2-D array both arrays will be sorted.
</div>

In [98]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Elements wise Sorting</strong>
<br>
• The argsort() method in NumPy sorts the array elements in ascending order and returns indices of the sorted elements.
</div>

In [99]:
arr = np.array([10, 2, 9, -1])
arg_sort = np.argsort(arr)
print("Sorted Array :", arr[arg_sort])
print("Sorted Index :", arg_sort)

Sorted Array : [-1  2  9 10]
Sorted Index : [3 1 2 0]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Matrix</font>
<br>
<br>
• A matrix is a two-dimensional data structure where numbers are arranged into rows and columns.
<br>
• The matrix is represented as 3x4 (pronounced "three by four") matrix because it has 3 rows and 4 columns.
<br>
• Python doesn't have a built-in type for matrices. However, we can treat a list of a list as a matrix.
<br>
• But, NumPy has matrix() method which is used to create a matrix from a 2-D array-like object.
</div>

In [100]:
#Creating a matrix from 2D array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_arr = np.matrix(arr)

print(matrix_arr)

#Accessing elements of a matrix
print(matrix_arr[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Matrix Operation</strong>
<br>
• The determinant of a matrix is a scalar value that provides information about the properties and behavior of the matrix.
<br>
• The np.linalg.det() function is used to compute the determinant of a square matrix.
</div>

In [101]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_arr = np.matrix(arr)

det_arr = np.linalg.det(matrix_arr)

print(det_arr)

0.0


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• The matmul() method is used to perform matrix multiplication in NumPy.
</div>

In [102]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

matrix1 = np.matrix(arr1)
matrix2 = np.matrix(arr2)

arr_multi = np.matmul(matrix1, matrix2)
print(arr_multi)

[[19 22]
 [43 50]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• The np.trace() function is used to return the sum of the diagonals of the matrix.
</div>

In [103]:
arr = np.array([[1,2],[3,4]])
matrix = np.matrix(arr)

result = np.trace(matrix)

print(matrix)
print(result)  

[[1 2]
 [3 4]]
5


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Transpose an Aarray</strong>
<br>
• The np.transpose() method swaps the axes of the given array similar to the transpose of a matrix in mathematics. 
<br>
• In the case of arrays with more than two dimensions, np.transpose() permutes the axes based on the given argument.
</div>

In [104]:
#By using transpose() function
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_arr = np.matrix(arr)

trans_arr = np.transpose(matrix_arr)

print("Array before Transpose :", arr)
print("Array after Transpose :", trans_arr)

Array before Transpose : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after Transpose : [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [105]:
#By using T function
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_arr = np.matrix(arr)

trans_arr = matrix_arr.T

print("Array before Transpose :", arr)
print("Array after Transpose :", trans_arr)

Array before Transpose : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after Transpose : [[1 4 7]
 [2 5 8]
 [3 6 9]]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Aggregation Functions</font>
<br>
<br>
• NumPy also performs aggregation functions. 
<br>
• In addition to min, max and sum, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation and more.
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> You can add axis() parameter to any function listed below.
</div>
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> Remember to add axis() only for 2D or above array.
</div>
</div>

In [106]:
#Min() Function
arr = np.array([1,2,3,4,5,6])
print(np.min(arr))

1


In [107]:
#Max() Function
arr = np.array([1,2,3,4,5,6])
print(np.max(arr))

6


In [108]:
#Sum() Function
arr = np.array([1,2,3,4,5,6])
print(np.sum(arr))

21


In [109]:
#Prod() Function
arr = np.array([1,2,3,4,5,6])
print(np.prod(arr))

720


In [110]:
#Mean() Function
arr = np.array([1,2,3,4,5,6])
print(np.mean(arr))

3.5


In [111]:
#Median() Function
arr = np.array([1,2,3,4,5,6])
print(np.median(arr))

3.5


In [112]:
#Percentile() Function
arr = np.array([1,2,3,4,5,6])
print(np.percentile(arr, 25))

2.25


In [113]:
#Quantile() Method
arr = np.array([1,2,3,4,5,6])
print(np.quantile(arr, 0.75))

4.75


In [114]:
#Var() Function
arr = np.array([1,2,3,4,5,6])
print(np.var(arr))

2.9166666666666665


In [115]:
#Std() Function
arr = np.array([1,2,3,4,5,6])
print(np.std(arr))

1.707825127659933


In [116]:
#Sqrt() Function
arr = np.array([1,2,3,4,5,6])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [117]:
#Square() Function
arr = np.array([1,2,3,4,5,6])
print(np.square(arr))

[ 1  4  9 16 25 36]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• The np.nanmean() method computes the arithmetic mean along the specified axis and ignores the NaNs (Not a Number).
<br>
• Computing Mean of an array having NaN Values in it, results in NaN as output. 
<br>
• But nanmean() function ignores NaN Values whie computing mean and provide the result.
</div>

In [118]:
#Nanmean() Function
arr = np.array([0, np.nan, np.nan, 1, 2, 3, 4, 5, 6, 7])

mean_arr = np.mean(arr)
nan_mean_arr = np.nanmean(arr)

print("Calculating mean with mean() function :", mean_arr)
print("Calculating mean with nanmean() function :", nan_mean_arr)

Calculating mean with mean() function : nan
Calculating mean with nanmean() function : 3.5


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy ufuncs</font>
<br>
<br>
<strong>What are ufuncs?</strong>
<br>
• ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.
<br>
<br>
<strong>Why use ufuncs?</strong>
<br>
• ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
<br>
• They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.
<br>
<br>
<strong>Add the Elements of Two Lists</strong>
<br>
→ list 1: [1, 2, 3, 4]
<br>
→ list 2: [4, 5, 6, 7]
</div>

In [119]:
#Without ufunc, we can use Python's built-in zip() method
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [120]:
#With ufunc, we can use the add() function
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]

z = np.add(x, y)

print(z)

[ 5  7  9 11]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Simple Arithmetic</font>
<br>
<br>
• You could use arithmetic operators + - * / directly between NumPy arrays.
<br>
• But we have functions in numpy that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.
<br>
<br>
<strong>Addition</strong>
<br>
• The add() function sums the content of two arrays and return the results in a new array.
</div>

In [121]:
#With add() function
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [122]:
#Without add() function
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(arr1 + arr2)

[30 32 34 36 38 40]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Subtraction</strong>
<br>
• The subtract() function subtracts the values from one array with the values from another array and return the results in a new array.
</div>

In [123]:
#With subtract() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [124]:
#Without subtract() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(arr1 - arr2)

[-10  -1   8  17  26  35]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Multiplication</strong>
<br>
• The multiply() function multiplies the values from one array with the values from another array and return the results in a new array.
</div>

In [125]:
#With multiply() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [126]:
#Without multiply() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(arr1 * arr2)

[ 200  420  660  920 1200 1500]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Division</strong>
<br>
• The divide() function divides the values from one array with the values from another array and return the results in a new array.
</div>

In [127]:
#With divide() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.divide(arr1, arr2)

print(newarr)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [128]:
#Without divide() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(arr1 / arr2)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Power</strong>
<br>
• The power() function rises the values from the first array to the power of the values of the second array and return the results in a new array.
</div>

In [129]:
#With power() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [130]:
#Without power() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

print(arr1 ** arr2)

[      1000    3200000  729000000 -520093696       2500          0]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Remainder</strong>
<br>
• Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array and return the results in a new array.
</div>

In [131]:
#With mod() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [132]:
#With remainder() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [133]:
#Without mod() or remainder() function
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

print(arr1 % arr2)

[ 1  6  3  0  0 27]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Quotient and Mod</strong>
<br>
• The divmod() function return both the quotient and the the mod. 
<br>
• The return value is two arrays, the first array contains the quotient and second array contains the mod.
</div>

In [134]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Absolute Values</strong>
<br>
• Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt abs() function.
</div>

In [135]:
#With absolute() function
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


In [136]:
#Without absolute() function
arr = np.array([-1, -2, 1, 2, 3, -4])
print(abs(arr))

[1 2 1 2 3 4]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">Rounding Decimals</font>
<br>
<br>
• There are primarily five ways of rounding off decimals in NumPy.
<br>
→ truncation
<br>
→ fix
<br>
→ rounding
<br>
→ floor
<br>
→ ceil
<br>
<br>
<strong>Truncation</strong>
<br>
• Remove the decimals and return the float number closest to zero. Use the trunc() and fix() functions.
</div>

In [137]:
#Using trunc() Method
arr1 = np.trunc([-3.1666, 3.6667])
print(arr1)

#Using fix() Method
arr2 = np.fix([-3.1666, 3.6667])
print(arr2)

[-3.  3.]
[-3.  3.]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Rounding</strong>
<br>
• The around() function increments preceding digit or decimal by 1 if num >= 5 else do nothing.
</div>

In [138]:
arr = np.around(3.1666, 2)
print(arr)

3.17


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Floor</strong>
<br>
• The floor() function rounds off decimal to nearest lower integer.
</div>

In [139]:
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Ceil</strong>
<br>
• The ceil() function rounds off decimal to nearest upper integer.
</div>

In [140]:
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Summations</font>
<br>
<br>
<strong>Summations</strong>
<br>
• What is the difference between summation and addition?
<br>
• Addition is done between two arguments whereas summation happens over n elements.
</div>

In [141]:
#Using add() function
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [142]:
#Using sum() function
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Summation Over an Axis</strong>
<br>
• If you specify axis=1, NumPy will sum the numbers with respect to the row.
<br>
• If you specify axis=0, NumPy will sum the numbers with respect to the columns.
</div>

In [143]:
#Using axis=1 (Row Wise)
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [144]:
#Using axis=0 (Column Wise)
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=0)

print(newarr)

[2 4 6]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Cummulative Sum</strong>
<br>
• Cummulative sum means partially adding the elements in array.
<br>
• Perfom partial sum with the cumsum() function.
<br>
• The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
</div>

In [145]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Differences</font>
<br>
<br>
<strong>Differences</strong>
<br>
• A discrete difference means subtracting two successive elements.
<br>
• To find the discrete difference, use the diff() function.
<br>
• For [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]
</div>

In [146]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
• We can perform this operation repeatedly by giving parameter n.
</div>

In [147]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)
print(newarr)

[  5 -30]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Products</font>
<br>
<br>
<strong>Products</strong>
<br>
• To find the product of the elements in an array, use the prod() function.
</div>

In [148]:
#Find the product of the elements of one array
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

24


In [149]:
#Find the product of the elements of two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Product Over an Axis</strong>
<br>
• If you specify axis=1, NumPy will return the product of each array.
</div>

In [150]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Cummulative Product</strong>
<br>
• Cummulative product means taking the product partially.
<br>
• Perfom partial sum with the cumprod() function.
<br>
• The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]
</div>

In [151]:
arr = np.array([5, 6, 7, 8])
newarr = np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<font color='#6a66bd' size="5px">NumPy Broadcasting</font>
<br>
<br>
• In NumPy, we can perform mathematical operations on arrays of different shapes. 
<br>
• An array with a smaller shape is expanded to match the shape of a larger one. This is called broadcasting.
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> In the example, we added two arrays with different dimensions.
</div>
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> Numpy automatically expands the size of arr1(1D) to match with the size of arr2(2D).
</div>

In [152]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

output = arr1 + arr2

print("Dimension of arr1 :", arr1.ndim)
print("Dimension of arr2 :", arr2.ndim)
print("Dimension of output :", result.ndim)

Dimension of arr1 : 1
Dimension of arr2 : 2
Dimension of output : 0


<div style="background-color:gainsboro; padding:8px; border:2px dotted black; border-radius:8px; font-family:verdana; line-height: 1.7em">
<strong>Compatibility Rules for Broadcasting</strong>
<br>
• Broadcasting only works with compatible arrays. NumPy compares a set of array dimensions from right to left.
<br>
• Every set of dimensions must be compatible with the arrays to be broadcastable. A set of dimension lengths is compatible when :
<br>
→ One of them has a length of 1
<br>
→ Or, they both are equal
<br>
<br>
<strong>Examples</strong>
<br>
<strong>Broadcastable Shapes</strong>
<br>
→ (6, 7) and (6, 7)
<br>
→ (6, 7) and (6, 1)
<br>
<strong>Non-Broadcastable Shapes</strong>
<br>
→ (6, 7) and (7, 6)
<br>
<br>
<strong>Broadcasting with Scalars</strong>
<br>
• We can also perform mathematical operations between arrays and scalars (single values).
<div style="background-color:#ADD8E6; padding:8px; border:1px solid #87CEEB; border-radius:4px;">
<strong>Note :</strong> In this example, NumPy automatically expands the scalar number to an 1-D array and then performs the element-wise addition.
</div>
</div>

In [153]:
arr = np.array([2,4,6,8,10])
num = 6
sum = arr + num
print(sum)

[ 8 10 12 14 16]


---

<p style="color:#6a66bd; text-align:center; font-weight:bold; font-family:verdana; font-size:25px;">Thanks 👏 for Visiting!</p>